project:
  type: website
  output-dir: ../docs
  render:
    - index.qmd
    - tutorials/ingestion.qmd
    - tutorials/species_pipeline.qmd
    - tutorials/cesnet_yolo_training.qmd
    - results.qmd


website:
  title: "Pollen detector"
  description: "Automated CZI Image Analysis and Pollen Classification"
  navbar:
    background: "#0d1117"
    foreground: "#f0f6fc"
    left:
      - href: index.qmd
        text: Home
      - href: tutorials/ingestion.qmd
        text: Ingestion Guide
      - href: tutorials/species_pipeline.qmd
        text: Species Pipeline
      - href: tutorials/cesnet_yolo_training.qmd
        text: General YOLO on CESNET
      - href: results.qmd
        text: Results
    right:
      - icon: github
        href: https://github.com/Pollination-Ecology-Group/colorado_pollen

format:
  html:
    theme: darkly
    highlight-style: github-dark
    css: styles.css
    code-fold: true
    code-summary: "Show the code"
    toc: true
    number-sections: true
